-- ============================================================
-- STAGING TABLE
-- Equity Gap Summary
-- Maternal Continuum of Care and Postnatal Equity in Nigeria
-- ============================================================


-- ------------------------------------------------------------
-- 1. CREATE STAGING TABLE
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS staging.equity_gap_summary (

    equity_variable TEXT,

    equity_dimension TEXT,

    indicator_variable TEXT,

    indicator TEXT,

    highest_group TEXT,

    highest_percent DOUBLE PRECISION,

    highest_ci_low DOUBLE PRECISION,

    highest_ci_high DOUBLE PRECISION,

    highest_group_n DOUBLE PRECISION,

    highest_reporting_status TEXT,

    lowest_group TEXT,

    lowest_percent DOUBLE PRECISION,

    lowest_ci_low DOUBLE PRECISION,

    lowest_ci_high DOUBLE PRECISION,

    lowest_group_n DOUBLE PRECISION,

    lowest_reporting_status TEXT,

    groups_compared DOUBLE PRECISION,

    caution_groups DOUBLE PRECISION,

    absolute_gap_pp DOUBLE PRECISION,

    relative_ratio DOUBLE PRECISION,

    relative_shortfall_percent DOUBLE PRECISION,

    comparison_status TEXT
);


-- ------------------------------------------------------------
-- 2. DOCUMENT TABLE
-- ------------------------------------------------------------

COMMENT ON TABLE staging.equity_gap_summary IS
'Staging table containing equity disparity summaries generated by the validated R analytical pipeline, including highest and lowest performing groups, absolute gaps, relative ratios and shortfall measures.';


-- ------------------------------------------------------------
-- 3. VERIFY TABLE CREATION
-- ------------------------------------------------------------

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'staging'
  AND table_name = 'equity_gap_summary';

SELECT COUNT(*) AS current_rows
FROM staging.equity_gap_summary;

SELECT COUNT(*) AS rows_loaded
FROM staging.equity_gap_summary;

SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT equity_dimension)
        AS equity_dimensions,

    COUNT(DISTINCT indicator_variable)
        AS indicators,

    COUNT(*) FILTER (
        WHERE equity_variable IS NULL
           OR equity_dimension IS NULL
           OR indicator_variable IS NULL
           OR indicator IS NULL
           OR highest_group IS NULL
           OR lowest_group IS NULL
    ) AS missing_key_fields,

    COUNT(*) FILTER (
        WHERE highest_percent < 0
           OR highest_percent > 100
           OR lowest_percent < 0
           OR lowest_percent > 100
    ) AS invalid_percentages,

    COUNT(*) FILTER (
        WHERE highest_ci_low > highest_ci_high
           OR lowest_ci_low > lowest_ci_high
    ) AS invalid_confidence_intervals,

    COUNT(*) FILTER (
        WHERE absolute_gap_pp < 0
    ) AS negative_absolute_gaps,

    COUNT(*) FILTER (
        WHERE relative_ratio < 0
    ) AS invalid_relative_ratios

FROM staging.equity_gap_summary;

SELECT
    comparison_status,
    COUNT(*) AS rows
FROM staging.equity_gap_summary
GROUP BY comparison_status
ORDER BY comparison_status;

SELECT
    equity_dimension,
    COUNT(*) AS comparisons,
    ROUND(AVG(absolute_gap_pp)::numeric, 2)
        AS mean_absolute_gap_pp,
    ROUND(MAX(absolute_gap_pp)::numeric, 2)
        AS largest_gap_pp
FROM staging.equity_gap_summary
GROUP BY equity_dimension
ORDER BY largest_gap_pp DESC;

INSERT INTO audit.data_load_log (
    source_file,
    target_schema,
    target_table,
    load_completed_at,
    rows_loaded,
    load_status
)
SELECT
    'equity_gap_summary.csv',
    'staging',
    'equity_gap_summary',
    CURRENT_TIMESTAMP,
    COUNT(*),
    'SUCCESS'
FROM staging.equity_gap_summary
WHERE NOT EXISTS (
    SELECT 1
    FROM audit.data_load_log
    WHERE source_file = 'equity_gap_summary.csv'
      AND target_schema = 'staging'
      AND target_table = 'equity_gap_summary'
      AND load_status = 'SUCCESS'
)
RETURNING
    load_id,
    source_file,
    target_table,
    rows_loaded,
    load_status;