-- ============================================================
-- STAGING TABLE
-- Equity Gap Summary
-- Maternal Continuum of Care and Postnatal Equity in Nigeria
-- ============================================================


-- ------------------------------------------------------------
-- 1. CREATE STAGING TABLE
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS staging.equity_gap_summary (

    equity_variable TEXT,

    equity_dimension TEXT,

    indicator_variable TEXT,

    indicator TEXT,

    highest_group TEXT,

    highest_percent DOUBLE PRECISION,

    highest_ci_low DOUBLE PRECISION,

    highest_ci_high DOUBLE PRECISION,

    highest_group_n DOUBLE PRECISION,

    highest_reporting_status TEXT,

    lowest_group TEXT,

    lowest_percent DOUBLE PRECISION,

    lowest_ci_low DOUBLE PRECISION,

    lowest_ci_high DOUBLE PRECISION,

    lowest_group_n DOUBLE PRECISION,

    lowest_reporting_status TEXT,

    groups_compared DOUBLE PRECISION,

    caution_groups DOUBLE PRECISION,

    absolute_gap_pp DOUBLE PRECISION,

    relative_ratio DOUBLE PRECISION,

    relative_shortfall_percent DOUBLE PRECISION,

    comparison_status TEXT
);


-- ------------------------------------------------------------
-- 2. DOCUMENT TABLE
-- ------------------------------------------------------------

COMMENT ON TABLE staging.equity_gap_summary IS
'Staging table containing equity disparity summaries generated by the validated R analytical pipeline, including highest and lowest performing groups, absolute gaps, relative ratios and shortfall measures.';


-- ------------------------------------------------------------
-- 3. VERIFY TABLE CREATION
-- ------------------------------------------------------------

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'staging'
  AND table_name = 'equity_gap_summary';